// <auto-generated />
using System;
using Dynamic_Schema_Social_Platform.Data.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dynamic_Schema_Social_Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dynamic_Schema_Social_Platform.Enteties.TalentAttribute", b =>
                {
                    b.Property<int>("AttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttributeId"));

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AttributeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TalentTypeId")
                        .HasColumnType("int");

                    b.HasKey("AttributeId");

                    b.HasIndex("TalentTypeId");

                    b.ToTable("TalentAttributes");
                });

            modelBuilder.Entity("Dynamic_Schema_Social_Platform.Enteties.TalentType", b =>
                {
                    b.Property<int>("TalentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TalentTypeId"));

                    b.Property<string>("TalentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TalentTypeId");

                    b.ToTable("TalentTypes");
                });

            modelBuilder.Entity("Dynamic_Schema_Social_Platform.Enteties.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePic")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Dynamic_Schema_Social_Platform.Enteties.UserTalent", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("TalentTypeId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "TalentTypeId");

                    b.HasIndex("TalentTypeId");

                    b.ToTable("UserTalents");
                });

            modelBuilder.Entity("Dynamic_Schema_Social_Platform.Enteties.UserTalentData", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("AttributeId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.ToTable("UserTalentData");
                });

            modelBuilder.Entity("Dynamic_Schema_Social_Platform.Enteties.TalentAttribute", b =>
                {
                    b.HasOne("Dynamic_Schema_Social_Platform.Enteties.TalentType", "TalentType")
                        .WithMany("TalentAttributes")
                        .HasForeignKey("TalentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TalentType");
                });

            modelBuilder.Entity("Dynamic_Schema_Social_Platform.Enteties.UserTalent", b =>
                {
                    b.HasOne("Dynamic_Schema_Social_Platform.Enteties.TalentType", "TalentType")
                        .WithMany("UserTalents")
                        .HasForeignKey("TalentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dynamic_Schema_Social_Platform.Enteties.User", "User")
                        .WithMany("UserTalents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TalentType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dynamic_Schema_Social_Platform.Enteties.UserTalentData", b =>
                {
                    b.HasOne("Dynamic_Schema_Social_Platform.Enteties.TalentAttribute", "TalentAttribute")
                        .WithMany("UserTalentData")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dynamic_Schema_Social_Platform.Enteties.User", "User")
                        .WithMany("UserTalentData")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TalentAttribute");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dynamic_Schema_Social_Platform.Enteties.TalentAttribute", b =>
                {
                    b.Navigation("UserTalentData");
                });

            modelBuilder.Entity("Dynamic_Schema_Social_Platform.Enteties.TalentType", b =>
                {
                    b.Navigation("TalentAttributes");

                    b.Navigation("UserTalents");
                });

            modelBuilder.Entity("Dynamic_Schema_Social_Platform.Enteties.User", b =>
                {
                    b.Navigation("UserTalentData");

                    b.Navigation("UserTalents");
                });
#pragma warning restore 612, 618
        }
    }
}
